const fs = require('fs');
const content = [
"'use strict';",
"",
"const express = require('express');",
"const router = express.Router();",
"const {",
"  getPaymentInstructions,",
"  createPaymentIntent,",
"  verifyPayment,",
"  syncAllPayments,",
"  finalizePayments,",
"  getStudentPayments,",
"  getAcceptedAssets,",
"  getOverpayments,",
"  getStudentBalance,",
"  getSuspiciousPayments,",
"  getPendingPayments,",
"  getRetryQueue,",
"} = require('../controllers/paymentController');",
"const { validateStudentIdParam, validateVerifyPayment } = require('../middleware/validate');",
"const idempotency = require('../middleware/idempotency');",
"",
"// Static routes first (before :studentId wildcard)",
"router.get('/accepted-assets', getAcceptedAssets);",
"router.get('/overpayments', getOverpayments);",
"router.get('/suspicious', getSuspiciousPayments);",
"router.get('/pending', getPendingPayments);",
"router.get('/retry-queue', getRetryQueue);",
"router.get('/balance/:studentId', validateStudentIdParam, getStudentBalance);",
"router.get('/instructions/:studentId', validateStudentIdParam, getPaymentInstructions);",
"router.get('/:studentId', validateStudentIdParam, getStudentPayments);",
"",
"// Idempotency enforced on mutating endpoints",
"router.post('/intent', idempotency, createPaymentIntent);",
"router.post('/verify', idempotency, verifyPayment);",
"",
"// Admin/internal",
"router.post('/sync', syncAllPayments);",
"router.post('/finalize', finalizePayments);",
"",
"module.exports = router;",
].join('\n');

fs.writeFileSync('backend/src/routes/paymentRoutes.js', content, 'utf8');
console.log('OK');
